version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
        - aws s3 sync https://github.com/AvidDabbler/walterkjenkins s3://www.walterkjenkins.com --delete